- type: antag
  id: Nukeops
  name: roles-antag-nuclear-operative-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 21600 # 6+-h
  - !type:DepartmentTimeRequirement
    department: Security
    time: 7200 # 2h

- type: antag
  id: NukeopsMedic
  name: roles-antag-nuclear-operative-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-agent-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 21600 # maybe 6h...
  - !type:RoleTimeRequirement
    role: JobChemist
    time: 18000 # 4+-h
  - !type:DepartmentTimeRequirement
    department: Security
    time: 720 # 2h

- type: antag
  id: NukeopsCommander
  name: roles-antag-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 21600 # idk :—Å
  - !type:DepartmentTimeRequirement
    department: Security
    time: 36000 # idk hrs
  # should be changed to nukie playtime when thats tracked (wyci)
