- type: job
  id: BKBPLATech
  name: job-name-silicon-BPLATech
  description: job-description-silicon-BPLATech
  playTimeTracker: BPLATech
  joinNotifyCrew: false
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1 hr
  - !type:DepartmentTimeRequirement
    department: Engineering
    time: 21600 # 1 hr
  icon: JobIconUnknown
  supervisors: job-supervisors-human
  canBeAntag: false
  jobEntity: BackmenDrone
  startingGear: RobotGear # for char preview only

- type: startingGear
  id: RobotGear
  equipment:
    head: ClothingHeadHatCardborg
    outerClothing: ClothingOuterCardborg
